### ISSUE TITLE
Research on the pricing of Hardware

### ISSUE THREAD

**Issue by Nishit-Gopani** [JJCSA/Infrastructure#3]
It can host two docker images (1. Backend 2. Keycloak)
One ECS - Two docker Images
Two separate ECS cluster(Preferable based on pricing)

**Comment by dharmil007** [comment]
bit.ly/jjc-aws-estimate

This is the link to the estimate. Let me know, if something else needs to be Added to this.

**Comment by Nishit-Gopani** [comment]
Thank you Dharmil for creating price estimate document :)
