### ISSUE TITLE
Research on Aurora or Postgresql

### ISSUE THREAD

**Issue by Nishit-Gopani** [JJCSA/Infrastructure#6]
Research on AWS Aurora and PostgreSql which one to use
Check on the pricing for both DB and compare( See which one is cost effective and easy to manage moving forward)[Price may be added by Dharmil on price estimation document]
If AWS Aurora is good see if it is compatible with PostgreSql or not

Note: Backend team is using PostgreSql as DB

**Comment by dharmil007** [comment]
I feel AWS Aurora is better than PostgreSQL on AWS. It is cost effective than Postgre sql and has better performance.

**Comment by Nishit-Gopani** [comment]
Based on our discussion we are moving forward with PostgreSQL for now
